// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PolarHab.DbAssets;

namespace PolarHab.Migrations
{
    [DbContext(typeof(ActivityContext))]
    partial class ActivityContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("PolarHab.DbAssets.Question", b =>
                {
                    b.Property<int>("QuestionKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CorrectDialogue")
                        .HasColumnType("text");

                    b.Property<string>("CorrectWhyDescription")
                        .HasColumnType("text");

                    b.Property<string>("CorrectWhyTitle")
                        .HasColumnType("text");

                    b.Property<string>("ImageName")
                        .HasColumnType("text");

                    b.Property<string>("QuestionDescription")
                        .HasColumnType("text");

                    b.Property<string>("QuestionName")
                        .HasColumnType("text");

                    b.Property<string>("Wrong1Dialogue")
                        .HasColumnType("text");

                    b.Property<string>("Wrong2Dialogue")
                        .HasColumnType("text");

                    b.Property<string>("Wrong3Dialogue")
                        .HasColumnType("text");

                    b.HasKey("QuestionKey");

                    b.ToTable("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
